### PR TITLE
Added dockerization for Web UI and instructions

### PR DESCRIPTION
**Pull request by ruoccofabrizio**
## Purpose

* Added dockerization for Web UI template, instructions for running the container and GitHub action for docker build and push

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by gmndrg** [comment]
This has been tested with customers already. This doesn't introduce a breaking change. Approving PR

**Comment by dereklegenzoff** [comment]
@gmndrg - is this ready to be merged?

**Comment by gmndrg** [comment]
> @gmndrg - is this ready to be merged?

@dereklegenzoff yes, it is. I have reviewed the instructions on it, it has no breaking changes and it has been tested by a few customers already with no issues.

**Comment by dereklegenzoff** [comment]
@gmndrg - merged! Thanks again for putting this together @ruoccofabrizio!

**Pull request merged**
